#!/usr/bin/env sh

ZK_PATH="$HOME/storage/shared/Zettelkasten"
echo "Opening Zettelkasten in $ZK_PATH"

cd "$ZK_PATH"

git pull origin main

CHANGES_EXIST="$(git status --porcelain | wc -l)"

if [ "$CHANGES_EXIST" -eq 0 ]; then
	exit 0
fi

git pull origin main
git add .
git commit -q -m "Last Sync: $(date +"%Y-%m-%d %H:%M:%S")"
git push origin main
